### ISSUE TITLE
Make codebook for column names in lokniti question data

### ISSUE THREAD

**Issue by JusticeV452** [dhmit/data-driven-democracy#13]
The new csv tables have variable names for the questions and variables but do not include the text corresponding to the values.

We need someone to create a csv file to be used as a table in the database that maps these variable names to their text using the questionnaires from https://www.lokniti.org/national-election-studies

- [x] 2004
- [x] 2009
- [x] 2014
- [x] 2019

**Comment by fleuriie** [comment]
Csv can be found here with different sheets for each year: https://docs.google.com/spreadsheets/d/1BVlY6EWBGR8kmpUQj8WwNU4WUEBHTvDjTFDg4t565bk/edit?usp=sharing pending integration into the code

**Comment by JusticeV452** [comment]
Thanks!
